# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.8"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.4.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-3.11" # why don't they have tags/versions??

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
  
  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    unused-packages = false

[[override]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
