# This CR deploys Jaeger and Elasticsearch
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      resources:
    esIndexCleaner:
      eabled: true
      schedule: "*/30 * * * *"
      numberOfDays: 1
