name: Examples E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: e2e-tests-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-e2e-examples-test-suite:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       kube-version:
       - "1.19"
       - "1.22"
    name: Run examples E2E tests
    steps:
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./hack/actions/e2e
        with:
          testsuite_name: examples
          kube_version: ${{ matrix.kube-version }}
